### PR TITLE
Chw 484 gather queue limits

### PR DESCRIPTION
**Pull request by bhansen112**

### CODE REVIEW

**Comment by araglu** [comment]
Max Wall Time is working well in my tests. 

- The logic with Max Nodes seems strange. The number it grabs is the maximum cores per node from the .csv file, not the max cores allowed in the queue (resources_max.ncpus in qstat). I think max cores should be compared against Nodes * Processes per Node. That might be difficult to quietly limit because it goes across two input fields, so this may need to be a warning instead.
- I'm conflicted about the wall time checks for hours, minutes, and seconds. I was able to enter in 00:75:00 before, and it worked somehow, and that was occasionally convenient. It also doesn't like when I have a single 0 for hours. On the other hand, I can't find any PBS documentation that describes syntax limits on walltime.
- I thought of another nice thing to check for (max_queued jobs), but I should make a new ticket out of it.

**Comment by araglu** [comment]
I am having trouble getting this to work in our Restart action. I see it connect to the system, run ":", run "echo $WORKDIR", and then fail with a stacktrace. I don't know why it never ran the qstat command. Here is the end of the stacktrace:
```
  File "...\pyuit\uit\gui_tools\submit.py", line 72, in update_max_wall_time_info
    self.max_wall_time = self.wall_time_maxes[self.queue]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sdc50** [comment]
@bhansen112 any idea what is going on with `Restart`?

**Comment by bhansen112** [comment]
@sdc50 yes, the `wall_time_maxes` variable wasn't being assigned from the `Restart` action
It doesn't seem like `update_hpc_connection_dependent_defaults` is being executed during a restart

**Comment by araglu** [comment]
Restart is working well now, and I really like the Max Processes. I won't have to cross-reference another website to figure out if my background or debug queue settings will work.

My only concern is that there are now 3 "qstat -Q" and 2 "qstat -Q -f -F json" commands being run, whereas it only ran one "qstat -Q" before.

**Review by araglu — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
